root: true
env:
  browser: true
  es2021: true
  node: true

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
  project: "./tsconfig.json"

settings:
  react:
    version: "detect"

plugins:
  - react
  - react-hooks 
  - "@typescript-eslint"

extends:
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "eslint:recommended"

rules:
  no-unused-vars: ["warn", { "argsIgnorePattern": "^_" }]
  react/react-in-jsx-scope: off # Required only for React < 17, not needed with React 17+
  react/jsx-uses-react: off
  react/prop-types: off # Disable prop-types as we use TypeScript
  react/jsx-uses-vars: error

overrides:
  - files:
      - "*.tsx"
      - "*.jsx"
 
      
